#!/usr/bin/env bash

# themes & plugins
git clone https://github.com/arcticicestudio/nord-tmux ~/.tmux/themes/nord-tmux
git clone https://github.com/tmux-plugins/tmux-resurrect ~/.tmux/plugins/tmux-resurrect

# reload
# tmux source-file ~/.tmux.conf
