#!/usr/bin/env bash

set -e

if [[ -z "${CI}" ]]; then
    declare -a apps=("git" "ruby" "go" "rust" "fzf" "alacritty" "tmux" "nvim" "VSCode" "Karabiner" "Snipaste")
else
    declare -a apps=("git" "ruby" "go")
fi

for app in "${apps[@]}"; do
    echo "Initializing $app"
    bash "./$app/init"
    if [[ -f "./$app/test" ]]; then
        echo "Testing $app"
        bash "./$app/test"
    fi
done
