#!/usr/bin/env bash

set -e

if [[ -z "${ENV}" ]]; then
    declare -a apps=("ruby" "go")
else
    declare -a apps=("fzf" "alacritty" "tmux" "neovim" "ruby" "go" "VSCode" "Shadowsocks" "Karabiner" "Snipaste")
fi

for app in "${apps[@]}"; do
    echo "Initializing $app"
    `./$app/init`
done
