#!/usr/bin/env bash

set -e

declare -a apps=("fzf" "alacritty" "tmux" "neovim" "ruby" "go" "VSCode" "Shadowsocks" "Karabiner" "Snipaste")

for app in "${apps[@]}"; do
    echo "Initializing $app"
    `./$app/init`
done
