#!/usr/bin/env bash

set -e

echo "Install Homebrew"
if test ! $(which brew); then
  echo "Installing homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Setup hostname"
sudo scutil --set HostName david-macbook

echo "Install with Brew Bundle"
set +e
brew bundle
set -e

echo "Setup workspace"
mkdir -p ~/dev
mkdir -p ~/work

echo "Setup Git"
cp ./git/work.gitconfig ~/work/.gitconfig
cp ./git/global.gitconfig ~/.gitconfig

echo "Setup Bash"
cp ./bash/.bashrc ~/.bashrc
cp ./bash/.bash_profile ~/.bash_profile

echo "Setup Zsh"
sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells'
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
cp ./zsh/crispy.zsh-theme ~/.oh-my-zsh/themes/
cp ./zsh/.zshrc ~/

echo "Setup applications"
echo "- fzf"
$(brew --prefix)/opt/fzf/install
echo "- neovim"
./neovim/neovim

echo "Link editors"
mkdir -p ~/Applications/
sudo ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
sudo ln -s /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code /usr/local/bin/code

echo "Setup Ruby"
./ruby/ruby

echo "Setup Go"
mkdir -p ~/go

echo "Setup Shadowsocks"
./Shadowsocks/init

echo "Setup sync folder"
mkdir -p ~/sync

echo "Setup macOS defaults"
./mac
