tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "heroku/brew"

brew "git"
brew "wget"
brew "mas"
brew "p7zip"
brew "dos2unix"
brew "vim"
brew "zsh"
brew "zsh-completions"
brew "proxychains-ng"
brew "ruby"
brew "go"
brew "cmake"
brew "fzf"
brew "mysql"
brew "sqlite"
brew "postgresql"
brew "youtube-dl"
brew "heroku"
brew "node"
brew "yarn"

cask "1password"
cask "alfred"
cask "google-chrome"
cask "sublime-text"
cask "visual-studio-code"
cask "font-source-code-pro"
cask "font-fira-code"
cask "caffeine"
cask "quip"
cask "workflowy"
cask "dash"
cask "karabiner-elements"
cask "shadowsocksx-ng"
cask "iina"
cask "neteasemusic"
cask "qqmusic"
cask "google-trends"
cask "appcleaner"
cask "spectacle"
cask "nutstore"
cask "telegram"

mas "WeChat", id: 836500024
mas "Unsplash Wallpapers", id: 1284863847
mas "Wunderlist", id: 410628904
mas "Microsoft OneNote", id: 784801555
mas "Bear", id: 1091189122
