#!/usr/bin/env bash

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cp ./vim/.vimrc ~/.vimrc
echo 'Run `vim +PlugInstall` to finish setup'
