#!/usr/bin/env bash

# vim-plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# conf
mkdir -p ~/.config/nvim
cp -r ./nvim/init.vim ./nvim/coc-settings.json ./nvim/plugin ~/.config/nvim/

# golang LSP
go get golang.org/x/tools/gopls@latest

# bash LSP
yarn global add bash-language-server

# ruby LSP
gem install solargraph
