brew install wget
brew install autojump
brew install mas
brew install p7zip
brew install dos2unix
brew install vim
brew install zsh
brew install proxychains-ng
brew install ruby
brew install go
brew install cmake
brew install fzf
brew cask install iina
brew cask install font-source-code-pro
