#!/usr/bin/env bash

set -e

if [[ -z "${CI}" ]]; then
    declare -a apps=("git" "ruby" "go" "rust" "fzf" "alacritty" "tmux" "nvim" "VSCode")
    # Optional: bash
else
    declare -a apps=("git" "ruby" "go")
fi

for app in "${apps[@]}"; do
    echo "Initializing $app"
    if [[ -f "./app/$app/init" ]]; then
        bash "./app/$app/init"
    fi
    if [[ -f "./app/$app/test" ]]; then
        echo "Testing $app"
        bash "./app/$app/test"
    fi
done
