#!/usr/bin/env bash

# Run `nvim` to trigger plugin install.
nvim

# Install formatters & linters (language servers are ensured by mason-lspconfig).
nvim '+MasonInstall luacheck markdownlint revive stylua shfmt yamllint'
