#!/usr/bin/env bash

# Run `nvim` to trigger plugin install.
nvim --headless "+Lazy! sync" +qa

# Install formatters & linters (language servers are ensured by mason-lspconfig).
nvim --headless '+MasonInstall luacheck markdownlint revive stylua shfmt yamllint' +qa
