#!/usr/bin/env bash

echo "Setup Zsh"
sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells'
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
cp ./zsh/crispy.zsh-theme ~/.oh-my-zsh/themes/
cp ./zsh/.zshrc ~/
