name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: run
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - name: build
        run: bash ./bootstrap
      - name: Test
        run: bash ./test
      - name: ShellCheck
        run: bash ./check
